#include <stdio.h>

char array[30000];
char *pointer = array;
int main()
{
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    *(pointer++);
    (*pointer)++;
    *(pointer++);
    *(pointer++);
    *(pointer++);
    *(pointer++);
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    *(pointer++);
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    (*pointer)++;
    *(pointer--);
    *(pointer--);
    *(pointer--);
    *(pointer--);
    *(pointer--);
    *(pointer--);
    while (*pointer)
    {
        *(pointer++);
        while (*pointer)
        {
            *(pointer++);
            *(pointer++);
            *(pointer++);
            *(pointer++);
            *(pointer++);
            *(pointer++);
            (*pointer)++;
            *(pointer++);
            (*pointer)++;
            *(pointer--);
            *(pointer--);
            *(pointer--);
            *(pointer--);
            *(pointer--);
            *(pointer--);
            *(pointer--);
            (*pointer)--;
        }
        *(pointer++);
        *(pointer++);
        *(pointer++);
        *(pointer++);
        *(pointer++);
        *(pointer++);
        *(pointer++);
        while (*pointer)
        {
            *(pointer--);
            *(pointer--);
            *(pointer--);
            *(pointer--);
            *(pointer--);
            *(pointer--);
            *(pointer--);
            (*pointer)++;
            *(pointer++);
            *(pointer++);
            *(pointer++);
            *(pointer++);
            *(pointer++);
            *(pointer++);
            *(pointer++);
            (*pointer)--;
        }
        *(pointer--);
        while (*pointer)
        {
            *(pointer++);
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            while (*pointer)
            {
                (*pointer)--;
                *(pointer--);
                (*pointer)--;
                while (*pointer)
                {
                    *(pointer++);
                    *(pointer++);
                    (*pointer)++;
                    *(pointer++);
                    (*pointer)++;
                    *(pointer--);
                    *(pointer--);
                    *(pointer--);
                    (*pointer)--;
                }
                *(pointer++);
                *(pointer++);
                *(pointer++);
                while (*pointer)
                {
                    *(pointer--);
                    *(pointer--);
                    *(pointer--);
                    (*pointer)++;
                    *(pointer++);
                    *(pointer++);
                    *(pointer++);
                    (*pointer)--;
                }
                (*pointer)++;
                *(pointer--);
                while (*pointer)
                {
                    *(pointer++);
                    while (*pointer)
                    {
                        (*pointer)--;
                    }
                    *(pointer--);
                    while (*pointer)
                    {
                        (*pointer)--;
                    }
                }
                *(pointer++);
                while (*pointer)
                {
                    *(pointer--);
                    *(pointer--);
                    while (*pointer)
                    {
                        *(pointer++);
                        *(pointer++);
                        *(pointer++);
                        (*pointer)++;
                        *(pointer--);
                        *(pointer--);
                        *(pointer--);
                        (*pointer)--;
                    }
                    *(pointer++);
                    *(pointer++);
                    while (*pointer)
                    {
                        (*pointer)--;
                    }
                }
                *(pointer--);
                *(pointer--);
            }
            *(pointer++);
            *(pointer++);
            *(pointer++);
            while (*pointer)
            {
                *(pointer++);
                *(pointer++);
                (*pointer)++;
                *(pointer++);
                (*pointer)++;
                *(pointer--);
                *(pointer--);
                *(pointer--);
                (*pointer)--;
            }
            *(pointer++);
            *(pointer++);
            *(pointer++);
            while (*pointer)
            {
                *(pointer--);
                *(pointer--);
                *(pointer--);
                (*pointer)++;
                *(pointer++);
                *(pointer++);
                *(pointer++);
                (*pointer)--;
            }
            (*pointer)++;
            *(pointer--);
            while (*pointer)
            {
                *(pointer++);
                while (*pointer)
                {
                    (*pointer)--;
                }
                *(pointer--);
                while (*pointer)
                {
                    (*pointer)--;
                }
            }
            *(pointer++);
            while (*pointer)
            {
                *(pointer--);
                *(pointer--);
                (*pointer)++;
                *(pointer++);
                *(pointer++);
                while (*pointer)
                {
                    (*pointer)--;
                }
            }
            *(pointer--);
            *(pointer--);
            *(pointer--);
            *(pointer--);
            *(pointer--);
            *(pointer--);
            *(pointer--);
        }
        *(pointer++);
        *(pointer++);
        *(pointer++);
        *(pointer++);
        *(pointer++);
        while (*pointer)
        {
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            (*pointer)++;
            printf("%c", *pointer);
            while (*pointer)
            {
                (*pointer)--;
            }
        }
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        *(pointer--);
        while (*pointer)
        {
            (*pointer)--;
            *(pointer++);
            (*pointer)--;
            *(pointer--);
        }
        *(pointer++);
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        (*pointer)++;
        printf("%c", *pointer);
        while (*pointer)
        {
            (*pointer)--;
        }
        *(pointer--);
        *(pointer--);
        *(pointer--);
        *(pointer--);
        *(pointer--);
        *(pointer--);
        *(pointer--);
        *(pointer--);
        *(pointer--);
        *(pointer--);
        *(pointer--);
        *(pointer--);
        while (*pointer)
        {
            *(pointer++);
            *(pointer++);
            *(pointer++);
            (*pointer)++;
            *(pointer++);
            (*pointer)++;
            *(pointer--);
            *(pointer--);
            *(pointer--);
            *(pointer--);
            (*pointer)--;
        }
        *(pointer++);
        *(pointer++);
        *(pointer++);
        *(pointer++);
        while (*pointer)
        {
            *(pointer--);
            *(pointer--);
            *(pointer--);
            *(pointer--);
            (*pointer)++;
            *(pointer++);
            *(pointer++);
            *(pointer++);
            *(pointer++);
            (*pointer)--;
        }
        *(pointer--);
        (*pointer)--;
        while (*pointer)
        {
            *(pointer++);
            *(pointer++);
            printf("%c", *pointer);
            *(pointer++);
            printf("%c", *pointer);
            *(pointer--);
            *(pointer--);
            *(pointer--);
            while (*pointer)
            {
                (*pointer)--;
            }
        }
        *(pointer--);
        *(pointer--);
        while (*pointer)
        {
            *(pointer++);
            *(pointer++);
            (*pointer)++;
            *(pointer++);
            (*pointer)++;
            *(pointer--);
            *(pointer--);
            *(pointer--);
            (*pointer)--;
        }
        *(pointer++);
        *(pointer++);
        *(pointer++);
        while (*pointer)
        {
            *(pointer--);
            *(pointer--);
            *(pointer--);
            (*pointer)++;
            *(pointer++);
            *(pointer++);
            *(pointer++);
            (*pointer)--;
        }
        *(pointer--);
        *(pointer--);
        while (*pointer)
        {
            *(pointer--);
            (*pointer)++;
            *(pointer++);
            (*pointer)--;
        }
        *(pointer++);
        while (*pointer)
        {
            *(pointer--);
            (*pointer)++;
            *(pointer++);
            (*pointer)--;
        }
        *(pointer--);
        *(pointer--);
        *(pointer--);
        (*pointer)--;
    }
}
